#!/bin/bash
mkdir -p ./icinga/{etc, data}
sudo docker-compose up -d  && echo -e "object ApiUser \"workshop\" {\n  password = \"workshop\"\n  permissions = [ \"*\" ]\n}"  > ./icinga/etc/conf.d/workshop.conf && docker exec -d icinga2 service icinga2 restart
